mozilla-releng/relengdocs

- software.rst
@lundjordan when you have a chance (no rush), would you mind having a look at this?
> Fix some of the text explaining mozharness

- flows.rst
- jobs_not_starting.rst
- procedures/TCW_RelEng.rst
- releng101/checkin-to-builds.rst
- schedulerdb.rst
- software.rst
- statusdb.rst
> tbpl -> treeherder

- procedures/mobile-automation-setup.rst
Don't merge this PR - the "actual" PR-ing of this documentation will occur after the [docs RFC](https://github.com/mozilla-releng/releng-rfcs/pull/7) is resolved.
[Rendered](https://github.com/mitchhentges/build-relengdocs/blob/dont-merge-automation-instructions/procedures/automation-android-setup.md)
> Android Automation setup docs - for review

- signing/adhoc_signing.rst
Mainly to link to the "how to request" doc.
> update adhoc docs

- procedures/Testing_Autograph.rst
- procedures/release-duty/merge-duty/merge_duty.rst
also fix the l10n bumper link.
> update autograph stage test docs

- procedures/mobile_automation_setup.rst
> how to gradle

- procedures/misc-operations/rotate-hg-cert.rst
- procedures/release-duty/index.rst
I'll create releng calendar reminders on 2021.10.31 (expiration date) as well as 2021.09.30 (1 mo before expiration) with notifications, and link to these docs, once this lands.
> Hgmo cert rotation docs

- procedures/release-duty/desktop/esr-to-esr-updates.rst
- procedures/release-duty/desktop/ubuntu-snap.rst
- procedures/release-duty/index.rst
quick cleanup based on email feedback
> first round of updates to releaseduty docs

- procedures/mobile_automation_setup.rst
I don't know how much of the pushapk docs are still accurate; ideally, we can test using the scriptworkers without doing much of this. I removed the portions I knew were out of date.
> staging mobile docs

- procedures/release-duty/desktop/flathub-flatpak.rst
More details in RELENG-56 JIRA ticket.
> Point Flathub instructions to SOPS repo

- signing/index.rst
- signing/rotate_gpg_signing_key.rst
very rough, but it's better than nothing
> Add rough instructions on GPG key rotation

- README
- maintaining_these_docs.rst
- procedures/accounts_setup.rst
- procedures/index.rst
- procedures/mobile_automation_setup.rst
I had a heck of a time getting android sdk/gradle to run locally for Focus, so hopefully this will save someone a headache in the future!
> Update mobile section and tweak some other sections

- procedures/release-duty/index.rst
Minor styling/syntax refactor, spelling, etc
Updated links to taskcluster
Refactor taskcluster CLI instructions
> Update release-duty index

- procedures/accounts_setup.md
- releng_changelog.md
Also fix mailing list warnings
> Update changelog for bug 1747280

- taskcluster/index.rst
- taskcluster/known_problems.rst
This will initially contain a few gotchas that came up in the
releaseduty post-mortem today.
> Add a 'known_problems' section to Taskcluster Administration

- procedures/release-duty/merge-duty/merge_duty.rst
I meant to check this in a while ago and forgot... but I think this part of merge duty could use clarification.
> Make merge duty sections clearer

- taskcluster/how_tasks_are_triggered.rst
- taskcluster/index.rst
I had to dig quite a bit to figure some of this stuff out to document it, so this is not 100% guaranteed to be accurate, especially the pulse / tc-github portions, but hopefully having it should be better than not.
> task triggering

- taskcluster/how_tasks_are_triggered.rst
This came up in channel -- others weren't aware that this feature
exists. I thought it would be good to document both its existence and
its limitations.
> document taskcluster_yml_repo

- taskcluster/fxci_upgrades.rst
- taskcluster/index.rst
- taskcluster/tc_staging.rst
Initial pass. We can update these as the process changes.
> FirefoxCI cluster upgrade docs

- explanations/index.rst
- explanations/slide_decks.rst
What I've found so far, at least.
> add slide deck links

- procedures/release-duty/index.rst
I realized the docs were slightly out of date in regard to Ship-It and Balrog.
> Update day 1 checklist with latest instructions

- how-tos/add-scriptworker-script.rst
- how-tos/index.rst
I have tried to re-format and capture the "wisdom" from bug 1745203. It's all a bit stale in my memory at this point, but hopefully others can add details and more tips as they add their own scripts.
> Add a how-to for adding a new script to scriptworker-scripts.

- procedures/release-duty/merge-duty/merge_duty.rst
Updating ShipIt section of Merge Day documentation
> Update ShipIt section of Merge Day documentation

- how-tos/l10n/index.rst
- how-tos/l10n/l10n-bumper.rst
- how-tos/l10n/l10n-cross-channel.rst
- reference/index.rst
Plus some other misc l10n changes.
> l10n cross-channel docs

- explanations/index.rst
- explanations/releng_environments.rst
- procedures/Testing_Autograph.rst
- procedures/release-duty/desktop/staging-release.rst
Saw some confusion about this a few weeks back.
> releng environments

- signing/rotate_gpg_signing_key.rst
I _think_ this covers everything we can write down publicly....
> Update GPG rotation docs with excrutiating detail.

- procedures/release-duty/merge-duty/merge_new_esr_branch.rst
I'm not sure this really belongs under merge-duty since most of it is outside merge days, but leaving it where it is for now.
> Flesh out new-esr-branch doc some more

- how-to/releaseduty/merge-duty/merge_new_esr_branch.rst
> Update docs for new esr

- how-to/taskcluster/uploading_an_image.rst
Remove mentions of `decision-mobile`, and add some notes about `gecko_decision`.
> Update how-to for decision image uploads (bug 1865788)

- explanations/best-practices/code-reviews.rst
- explanations/best-practices/index.rst
This page encompasses what the team discussed 3 weeks ago. 
Let's do a first pass of review on this. I'll get approval from the team before merging.
> Add guidelines on code reviews on the team

- how-to/taskcluster/ci_admin.rst
- how-to/taskcluster/tc_staging.rst
See https://github.com/mozilla-releng/fxci-config/pull/73
> Add note about needing a GITHUB_TOKEN to run ci-admin diff/apply

- tutorials/accounts_setup.md
Fixes a dead link, a typo and adds some instruction on how to get access to the different mobile stores if required.
> Day 1 checklist fixes

- how-to/rotate/gpg_signing_key.rst
This is an attempt mostly to clean them up a bit and remove parts I know to be outdated.
> rough updates to gpg docs

- how-to/rotate/gpg_signing_key.rst
- add pointer to this year's rotation bug and blog post
- reorder things slightly so the published KEY file is updated early in the process
> Small update to gpg signing key rotation howto

- explanations/best-practices/bug-triage.rst
Components changed at some point.
> chore: update bug triage link

- tutorials/accounts_setup.md
I had a good read over this. Most of it is still valid and relevant; some updates were warranted around Mercurial and the Gecko repository.
> update week 1 checklist
