mozilla-releng/relengdocs

release_workflows/fx_beta_release.rst, release_workflows/fx_ga_release.rst
sphinx-doc/sphinx#1788 is fixed in tree, but not released yet. For our
purposes, we need it deployed on read-the-docs.
=> Stop using captions until fix propagated.

procedures/release-duty/index.rst, signing/adhoc_signing.rst, signing/index.rst
As per our discussions in `Process and Handling of Firefox-CI administration requests` document.
=> Improve releaseduty docs; add adhoc signing reference

addons/index.rst, addons/langpacks.rst, addons/xpi-signing.rst, index.rst
I also rename the `Addon Submission Pipeline` to `Langpack submission pipeline`, just to clarify and differentiate from the xpi signing pipeline.
=> add xpi signing doc links

procedures/misc-operations/upload-to-internal-pypi.rst
At some point we'll perform a larger cleanup in docs. Until then, adding a pointer for now.
=> Add pointers to PyPI upload from wiki

procedures/mobile_automation_setup.rst
Follows https://github.com/mozilla/build-relengdocs/pull/49 up.
=> Gradle: Do no install it globally

procedures/release-duty/merge-duty/merge_duty.rst
Once https://bugzilla.mozilla.org/show_bug.cgi?id=1658553 is fixed, Aryx will be able to trigger beta simulations and try staging releases before mergeduty, removing this step for RelEng's mergeduty. 
CC: @Archaeopteryx
=> DO NOT MERGE YET - Bug 1658553 - remove staging releases as part of mergeduty

procedures/release-duty/merge-duty/merge_new_esr_branch.rst
I tried to update the docs with esr78 info, which might be out of date.
Whoever does esr91 may want to redo this documentation.
I mainly did this to include new l10n-cross-channel docs.
=> update esr docs

procedures/release-duty/index.rst
* remove obsolete links
* clarify meetings and calendars
* standardize on "ReleaseDuty" spelling
=> minor update to ReleaseDuty docs

procedures/mobile_automation_setup.rst, procedures/release-duty/merge-duty/merge_duty.rst, troubleshooting.rst
Noticed some errors when running `make html` after blowing away `_build`.
=> fix errors

procedures/release-duty/merge-duty/merge_duty.rst
We get some of these e-mails on both lists, but they're only consistently sent to release-drivers.
=> Update mergeduty docs with the correct mailing list to watch.

procedures/release-duty/merge-duty/merge_duty.rst
Adds a warning about idempotency issues in the merge day automation.
=> adds a warning about idempotency issues in the merge day automation

best-practices/handoffs.rst, best-practices/index.rst
A quick braindump of some best practices we had practiced in years past for multi-timezone multi-team incidents and chemspills.
These haven't been as critical for some number of years, since the automation has solved more and more of the previously-manual steps. But in case we do need to respond to an incident like this, this document may help guide us.
=> handoffs and incident response

procedures/mobile_automation_setup.rst, taskcluster/scopes.rst
It was merged into ci-configuration last year.
=> Remove references to the standalone ci-admin repo

procedures/release-duty/merge-duty/merge_duty.rst
It was hidden in the "bump mozilla-central" section which made it easy to miss when glancing at the docs.
=> merge-duty: move ship-geckoview trigger to its own section

procedures/accounts_setup.md
A few minor improvements based on my experience going through this document in the past month:
- Update some bug example links to newer versions, that are more up-to-date/complete
- Remove the explicit line about `cloudops-infra` (this is already granted when `mozilla-services` is granted).
- Add a note that you shouldn't expect to see teams that you already already a part of
- Remove notes about Ship it & Balrog access -- these are handled as part of LDAP group additions
- Add a new section about getting Balrog ACLs granted.
=> Minor updates to onboarding

procedures/accounts_setup.md
Now that we know where this access is controlled, we can just create PRs for it ourselves.
=> Add note about relengworker secrets access

addons/langpacks.rst, procedures/release-duty/desktop/staging-release.rst
The changes to staging release docs are:
- Recommending `staging` task set (otherwise you get a crapton of tests that are almost never relevant to RelEng changes)
- Recommending `--disable-pgo` to speed things up
- Recommending not to use partials, because they're too tricky to get right, and usually not relevant
- Minor cleanup of wording, formatting, warnings.
@gabrielBusta - the second commit of cleanup is just removing a reference to a missing screenshot in the langpack docs. Is there maybe a screenshot we can add instead of removing this?
=> Update staging release docs + minor cleanup

taskcluster/uploading_an_image.rst
Specifically:
- Drop references to local digests (these don't appear to exist until you push with modern Docker versions)
- Add note about $IMAGE_ID for taskgraph decision images
According to Matrix history, the former came up last time we did this as well. I'm not sure if these instructions every worked -- but they certainly don't now, and the only thing we use digests for is pinning images (and we only need the remote one for that).
=> Improvements to taskgraph image pushing docs.

how-to/l10n/langpacks.rst, procedures/release-duty/merge-duty/merge_duty.rst
* Fixed a link
* Moved things that happen on release day to their own section (current docs make it seem like they should happen at the same time as central/esr bumps)
* Simplified Ship It bump docs. IMO these are too wordy for what is supposed to be a how to. Feel free to disagree and push back though.
* Unrelated to merge day - removed a reference to a dead how-to.
* Added a note about trying to Ship It bumps on merge day part 2.
=> Minor improvements to release day docs

procedures/releng_bug_triage.md
Adds a page titled `RelEng Bug Triage` to document our on-going bug triage process.
It should probably say how to tag a `good-first-bug` too...
=> Adds releng_bug_triage.md

procedures/release-duty/merge-duty/merge_duty.rst
The existing docs are:
a) not complete
b) point at an incorrect example for Beta in merge day part 1
=> Add much more detailed documentation on expectations for tags during merge day operations

procedures/release-duty/merge-duty/merge_duty.rst
I noticed while doing merges today that the second tag happens as part of tag & bump (obviously...) not uplift.
=> Move expected mozilla-central tag to the correct section

procedures/release-duty/merge-duty/merge_duty.rst
Previously the wording was ambiguous around whether `mozilla-central` or `mozilla-beta` was the one bumped to XXX.0b1, which could confuse folks who aren't familiar with the release model.
=> Adjust wording in merge-duty response e-mail to be less confusing

conf.py, explanations/balrog/index.rst, explanations/best-practices/bug-triage.rst, explanations/l10n.rst, explanations/taskcluster/how_tasks_are_triggered.rst, how-to/create/new-scriptworker-script.rst, how-to/release/addons/openh264.rst, how-to/release/addons/widevine.rst, how-to/release/firefox/index.rst, how-to/releaseduty/desktop/staging-release.rst, how-to/taskcluster/index.rst, how-to/taskcluster/testing_relpro.rst
We have the intersphinx extension enabled, but never set up the external targets. This will allow us to more easily link to our other documentation pages.
=> fix: setup and use intersphinx mappings

how-to/releaseduty/desktop/staging-release.rst
- Remove references to production archive, now that staging releases don't depend on it in any way
- Remove reference to running staging releases ahead of RC, because we don't do it anymore
- Alter reference to "Mozilla VPN", because that term is ambiguous these days
=> Minor updates to staging release documentation

how-to/taskcluster/uploading_an_image.rst
build-decision no longer uses python 3.8, and updating its dependencies is now covered by pin.sh.
=> Update how-to for build-decision dependencies update (bug 1865683)

how-to/releaseduty/merge-duty/merge_duty.rst
geckoview now ships as part of the regular android nightly, to be picked up by reference-browser.  No need to trigger it manually since the firefox-android merge.
cc @rvandermeulen
=> Remove ship-geckoview step from merge duty

conf.py
Update conf.py as documented in the "deprecation of Sphinx context injection at build time" announcement:
https://about.readthedocs.com/blog/2024/07/addons-by-default/
=> set baseurl from environment on readthedocs

explanations/best-practices/code-reviews.rst
This is motivated by a whoopsie we had when a worker pool was removed which was asserted to be unused, but actually was, and the issue was not caught in review.
=> code review: add some verbiage around backing up assertions as a requester, and verifying them as a reviewer

tutorials/accounts_setup.md
I also changed the link to my request for releng ACLs as it's the same as the previous one, minus groups that weren't necessary at the time, with explanation on groups that aren't needed anymore.
=> Remove unnecessary ACLs from the documentation

how-to/releaseduty/desktop/esr-to-esr-updates.rst, how-to/releaseduty/index.rst
The list of people from releng is way out of date and one should just ask in channel instead of pinging a single person. The firefox snap is apparently not managed by us anymore and the link to `ubuntu-snap` was broken ages ago without anyone complaining.
=> Remove out of date sections

tutorials/accounts_setup.md
One shouldn't go through a bugzilla bug anymore but instead open a PR directly on the infra repository.
=> Update the steps to get access to Jenkins

tutorials/accounts_setup.md
If you're not part of that group, trying to trigger pipelines in jenkins results in 500s, see the linked issue.
=> Add a mention of the releng group in jenkins

how-to/test/index.rst, how-to/test/update-verify.rst
This is simple copy/paste from https://searchfox.org/mozilla-central/source/tools/update-verify/README.md, which is getting removed in https://phabricator.services.mozilla.com/D236937.
This shouldn't merge until the above patch is deployed.
=> add a page for how to run update verify locally

how-to/handle-emergencies/manually-beetmove.rst
This is still probably not ideal, but then again, uploading by hand is not ideal in the first place. I've moved the `apilint` credentials in the secrets repo to line up with the new docs here.
=> slightly improve documentation around manually uploading files

how-to/releaseduty/merge-duty/merge_duty.rst
I'm not 100% sure this change is correct, but reading the Merge Duty doc in its current state, things don't align in a way that makes sense to me.
With the proposed changes in this PR, it seems to make more sense.
=> Merge Duty: clarify BETA_BASE/END tags

how-to/releaseduty/merge-duty/merge_new_esr_branch.rst
[Bug 1922671](https://bugzilla.mozilla.org/show_bug.cgi?id=1922671) removed cross-channel and the l10n stuff now lives on github at https://github.com/mozilla-l10n/firefox-l10n-source
=> Update documentation around cross channel for new ESRs

how-to/release/mozillavpn.rst
The current instructions don't work, and end up filtering away the runs we want :(.
=> fix: mozilla vpn release docs for linux after github UI change

how-to/releaseduty/index.rst
I'm the only one in there and I haven't seen anything we'd need to pay attention to in the past 6+ months. When issues arise, dicsussions should happen in #releaseduty.
=> Remove the mention to tbdrivers in channels to pay attention to

tutorials/accounts_setup.md
Check attached bug for reference : https://bugzilla.mozilla.org/show_bug.cgi?id=1816907.
=> Removed mozilla-l10n from onboarding docs
